baseURL: "https://mojtabamozaffar.github.io" 
title: Mojtaba Mozaffar
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 5 
        - name: Robotics
          url: robotics/
          weight: 2
        - name: Papers
          url: papers/
          weight: 3
        - name: Hobbies
          url: hobbies/
          weight: 4 

params:
    description: "Welcome to my homepage! I am a senior applied scientist at Amazon Robotics and an ex-research professor at Northwestern Univeristy. My research interests includes computational physics, robotics, computer vision, and policy learning."
    author: Mojtaba Mozaffar
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","robotics","papers","hobbies"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Mojtaba Mozaffar
          subtitle: "Welcome to my homepage! I am a senior applied scientist at Amazon Robotics and an ex-research professor at Northwestern Univeristy. My research interests includes computational physics, robotics, computer vision, and policy learning."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Robotics
              url: robotics/
            - name: Papers
              url: papers/
            - name: Hobbies
              url: hobbies/

    socialIcons:
        - name: Resume
          url: Resume_Mojtaba_Mozaffar.pdf
        - name: Email
          url: mojtabamozaffar@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/mojtaba-mozaffar/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=94sfs8QAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/mojtabamozaffar

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Mojtaba Mozaffar"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2