baseURL: "https://mojtabamozaffar.github.io" 
title: Mojtaba Mozaffar
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

params:
    description: Welcome to my homepage! I am a Senior Applied Scientist at Amazon Robotics and a former Research Assistant Professor at Northwestern University. Over the past decade, I have worked on a range of exciting problems in robotics, computer vision, policy learning, and physics-informed AI. Feel free to reach out — I'm always happy to chat with like-minded people.
    author: Mojtaba Mozaffar
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Mojtaba Mozaffar
          subtitle: Welcome to my homepage! I am a Senior Applied Scientist at Amazon Robotics and a former Research Assistant Professor at Northwestern University. Over the past decade, I have worked on a range of exciting problems in robotics, computer vision, policy learning, and physics-informed AI. Feel free to reach out — I'm always happy to chat with like-minded people.
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160

    socialIcons:
        - name: Email
          url: mailto:mojtabamozaffar@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/mojtaba-mozaffar/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=94sfs8QAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/mojtabamozaffar

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Mojtaba Mozaffar"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2